### ISSUE TITLE
Vuex. Modules

### ISSUE THREAD

**Issue by IFLead** [Art9Studio/JumbleSweets-Frontend#2]
Создать модуль Vuex для товаров.
Добавить **3 товара**  для теста. 
Поля:
- Название
- Ссылка на изображение (брать из любого места)
- Цена
- Цена до скидки (может равняться текущей в случае, если нет скидки)
- В избранном? (Bool)

**Comment by Gumbeat** [comment]
16a326594670d0f73a26390e7c19dfb786edf1c6
