### ISSUE TITLE
Seo. Lite Version

### ISSUE THREAD

**Issue by IFLead** [Art9Studio/JumbleSweets-Frontend#4]
Установить, настроить плагин для страницы деталей товара.
[Качать здесь](https://github.com/declandewet/vue-meta)

**Comment by Gumbeat** [comment]
419464470396592b4da4096fa3611bffb30c69c8

**Comment by IFLead** [comment]
В коммите оставил комменты

**Comment by Gumbeat** [comment]
9dfbd9a7529336276ecbc068f89db7a1b6fe5ee5
