### ISSUE TITLE
Vuex. Package of Modules

### ISSUE THREAD

**Issue by IFLead** [Art9Studio/JumbleSweets-Frontend#6]
- [x] Добавить модуль для **категорий**, поля:
- id
- name
- count

- [x] Добавить модуль для **производителей**, поля:
- id
- name

- [x] Добавить модуль для **поводов**, поля:
- id
- name

- [x] Зарендерить это все на главной

**Comment by Gumbeat** [comment]
7e9822fe45b0f3f587029243eda0add13f0f00ab
